### ISSUE TITLE
Blank space is missed when inference

### ISSUE THREAD

**Issue by oggyfaker** [Topdu/OpenOCR#107]
Hi @Topdu , thank for your amazing repo. Training accuracy is very cool in my dataset. However, when i try inference model on my folder image , my text is missing the blank space like this. Could you tell me how to train model with  pretrained weight of SVTRv2-B along using new vocab i add ? 

![Image](https://github.com/user-attachments/assets/5eb0ed00-93eb-4669-a049-783d08eec172)

![Image](https://github.com/user-attachments/assets/67f8947d-4d14-4ef6-8263-790721e5435c)

In my setup training, i used pretrained model from [SVTRv2-B](https://github.com/Topdu/OpenOCR/blob/main/configs/rec/svtrv2/readme.md#11-models-and-results) and modify my new vocab list (have more charater than yours vocab). After training the accuracy have increased significantly. But my result is missing blank space character. 

**Here is my vocab txt file:** 
[New_Dict.txt](https://github.com/user-attachments/files/19538217/New_Dict.txt)

**And this is my config training:** 
[train_config.txt](https://github.com/user-attachments/files/19538263/train_config.txt)

**My inference config:** 
[infer_config.txt](https://github.com/user-attachments/files/19538273/infer_config.txt)

Hope to see your answer soon !

**Comment by Topdu** [comment]
You should set `Global`'s `use_space_char` to True, that has a higher priority.
```yaml
Global:
  device: gpu
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/svtrv2_b_simpson_ver3
  save_epoch_step:
  - 15
  - 1
  eval_batch_step:
  - 0
  - 500
  eval_epoch_step:
  - 0
  - 1
  cal_metric_during_train: true
  pretrained_model: /home/oggy/Desktop/AI_Simpson/OpenOCR/pretrained/svtrv2_b_gtv_rctc/best.pth
  checkpoints: null
  use_tensorboard: false
  infer_img: null
  character_dict_path: ./tools/utils/EN_symbol_dict.txt
  max_text_length: 25
  use_space_char: True # use_space_char: false
```
