### ISSUE TITLE
IGTR算法使用报错 ValueError: Sample larger than population or is negative

### ISSUE THREAD

**Issue by leduy-it** [Topdu/OpenOCR#111]
[2025/04/09 09:33:46] openrec INFO: finetune from checkpoint ./pretrained/igtr/best.pth
[2025/04/09 09:33:46] openrec INFO: run with torch 2.3.1 and device cuda:0
[2025/04/09 09:33:46] openrec INFO: During the training process, after the 0th epoch, an evaluation is run every 1 epoch
[2025/04/09 09:33:46] openrec INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
/opt/conda/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at /opt/conda/conda-bld/pytorch_1716905971132/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:84.)
  return F.conv2d(input, weight, bias, self.stride,
/opt/conda/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:143: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
[2025/04/09 09:33:51] openrec INFO: epoch: [1/100], global_step: 10, lr: 0.000004, acc: 0.000000, norm_edit_dis: 0.000000, num_samples: 32.000000, loss: 14.089334, loss1: 9.133345, loss2: 0.310344, loss3: 0.663158, loss4: 3.960222, avg_reader_cost: 0.08823 s, avg_batch_cost: 0.46786 s, avg_samples: 32.0, ips: 68.39689 samples/s, eta: 335 days, 1:15:38
Traceback (most recent call last):
Traceback (most recent call last):
  File "/workspace/OpenOCR/tools/train_rec.py", line 40, in <module>
    main()
  File "/workspace/OpenOCR/tools/train_rec.py", line 36, in main
    trainer.train()
  File "/workspace/OpenOCR/tools/engine/trainer.py", line 259, in train
    for idx, batch in enumerate(self.train_dataloader):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/OpenOCR/tools/data/lmdb_dataset.py", line 139, in __getitem__
    return self.__getitem__(np.random.randint(self.__len__()))
  File "/workspace/OpenOCR/tools/data/lmdb_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "/workspace/OpenOCR/openrec/preprocess/__init__.py", line 83, in transform
    data = op(data)
  File "/workspace/OpenOCR/openrec/preprocess/igtr_label_encode.py", line 70, in __call__
    encoder_result = self.encode(text)
  File "/workspace/OpenOCR/openrec/preprocess/igtr_label_encode.py", line 251, in encode
    none_char_index = random.sample(
  File "/opt/conda/lib/python3.10/random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

```
Global:
  device: gpu
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/svtr_base_igtr_ch_aug
  save_epoch_step: 1
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  eval_epoch_step: [0, 1]
  cal_metric_during_train: False
  pretrained_model: ./output/rec/igtr_ch_aug_model_log/best.pth
  checkpoints:
  use_tensorboard: false
  infer_img:
  # for data or label process
  character_dict_path: &character_dict_path ./tools/utils/chinese_6800_character.txt
  # ./tools/utils/EN_symbol_dict.txt # 96en
  # ./tools/utils/ppocr_keys_v1.txt  # ch
  max_text_length: &max_text_length 100
  use_space_char: &use_space_char False
  save_res_path: ./output/rec/predicts_igtr_ch_aug.txt
  use_amp: True

Optimizer:
  name: AdamW
  lr: 0.0005 # 2gpus 256bs/gpu
  weight_decay: 0.05
  filter_bias_and_bn: True

LRScheduler:
  name: OneCycleLR
  warmup_epoch: 3
  cycle_momentum: False

Architecture:
  model_type: rec
  algorithm: BGPD
  in_channels: 3
  Transform:
  Encoder:
    name: SVTRNet
    img_size: [3, 48, 800]
    out_char_num: 25
    out_channels: 384
    patch_merging: 'Conv'
    embed_dim: [128, 256, 384]
    depth: [6, 6, 6]
    num_heads: [4, 8, 12]
    mixer: ['Conv','Conv','Conv','Conv','Conv','Conv', 'Conv','Conv', 'Global','Global','Global','Global','Global','Global','Global','Global','Global','Global']
    local_mixer: [[5, 5], [5, 5], [5, 5]]
    last_stage: False
    prenorm: True
    sub_k: [[1, 1], [2, 1]]
  Decoder:
    name: IGTRDecoder
    dim: 384
    vis_seq: 256
    num_layer: 1
    ar: False
    refine_iter: 0
    next_pred: False
    pos2d: false
    ds: false
    ch: True
    # pos_len: False
    # rec_layer: 1


Loss:
  name: IGTRLoss

PostProcess:
  name: IGTRLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: LMDBDataSet
    data_dir: ../dataset/train
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - PARSeqAug:
      - IGTRLabelEncode: # Class handling label
          k: 8
          prompt_error: False
          ch: True
          rare_file: ./rare_char.txt
          siml_file: ./siml_char.txt
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - SVTRResize:
          image_shape: [3, 48, 800]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'prompt_pos_idx_list',
          'prompt_char_idx_list', 'ques_pos_idx_list', 'ques1_answer_list',
          'ques2_char_idx_list', 'ques2_answer_list', 'ques3_answer', 'ques4_char_num_list',
          'ques_len_list', 'ques2_len_list', 'prompt_len_list', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ../dataset/eval
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - ARLabelEncode: # Class handling label
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - SVTRResize:
          image_shape: [3, 48, 800]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 4

```
newest main branch
