### ISSUE TITLE
If I want to train one epoch only, how to set lr?

### ISSUE THREAD

**Issue by nissansz** [Topdu/OpenOCR#27]
Optimizer:
name: AdamW
beta1: 0.9
beta2: 0.999
epsilon: 1.e-8
weight_decay: 0.05
no_weight_decay_name: norm
one_dim_param_no_weight_decay: True
lr:
name: Cosine
learning_rate: 0.001 # 8gpus 192bs
warmup_epoch: 5

**Comment by ir2718** [comment]
Hi,

can't you just achieve this by setting the `lr` in the config to your preferred value and removing the `warmup_epoch`?

```
Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.e-8
  weight_decay: 0.05
  no_weight_decay_name: norm
  one_dim_param_no_weight_decay: True
  name: Cosine
  lr: 0.001 # 8gpus 192bs
  warmup_epoch: 0
```
