### ISSUE TITLE
使用infer_rec时出现问题

### ISSUE THREAD

**Issue by super-tian** [Topdu/OpenOCR#71]
使用infer_rec + svtrv2推理单张图片时，出现问题：

推理代码：
```
from tools.infer_rec import OpenRecognizer
import yaml
from PIL import Image

config = yaml.load(open('/home/server/python/other_work/OCR/OpenOCR/models/svtrv2_smtr_gtc_ch/config.yml', 'r', encoding='utf-8'), Loader=yaml.FullLoader)
ocr = OpenRecognizer(config=config)
image = Image.open("/home/server/python/other_work/OCR/OpenOCR/test.jpg")
ocr(img_numpy=image)
```

![image](https://github.com/user-attachments/assets/ec2d2dd7-4014-4df6-bb69-0c46f1d28e99)

推测是因为使用了ctc + gtc 解码，但是没进行融合或加权，一个图片推理出现了两个结果；最后输出的部分也出现了问题：

![image](https://github.com/user-attachments/assets/1b050664-b88c-4bd5-b3ed-a772f34d0aec)
--- 
![image](https://github.com/user-attachments/assets/7bfa0a9d-4aab-43b5-9fb0-f91a212b59de)

**Comment by Topdu** [comment]
The following changes to the configuration file are required for svtrv2 to perform inference:
```yaml
...
  Decoder:
    name: GTCDecoder
    infer_gtc: False # True to False
    detach: False
    gtc_decoder:
...

Loss:
  name: CTCLoss # GTCLoss to CTCLoss
  # ctc_weight: 0.1 # delete
  # gtc_loss: # delete
   #  name: SMTRLoss # delete

PostProcess:
  name: CTCLabelDecode # GTCLabelDecode to CTCLabelDecode
  # gtc_label_decode: # delete
    # name: SMTRLabelDecode # delete
    # next_mode: *next # delete
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char

Metric:
  name: RecMetric # RecGTCMetric to RecMetric
  main_indicator: acc
  # is_filter: True

...

Eval:
  dataset:
    name: RatioDataSetTVResize
    ds_width: True
    padding: False
    data_dir_list: ['../benchmark_bctr/benchmark_bctr_test/scene_test']
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - CTCLabelEncode: # GTCLabelEncode to CTCLabelEncode
          # gtc_label_encode: # delete
            # name: ARLabelEncode # delete
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - KeepKeys:
          # keep_keys: ['image', 'label', 'length', 'ctc_label', 'ctc_length'] to
          keep_keys: ['image', 'label', 'length']
  sampler:
    name: RatioSampler
    scales: [[128, 32]] # w, h
    # divide_factor: to ensure the width and height dimensions can be devided by downsampling multiple
    first_bs: *bs
    fix_bs: false
    divided_factor: [4, 16] # w, h
    is_training: False
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: *bs
    max_ratio: *max_ratio
    num_workers: 4
```
