### ISSUE TITLE
同一数据集下， CPPD在 paddleocr 和 openocr 训练效果有明显差异

### ISSUE THREAD

**Issue by yjc11** [Topdu/OpenOCR#86]
使用两个框架训练时 CPPD 已发现以下 diff：
1. OpenOCR默认的 config 中，Decoder num_layer 默认为 3，paddleocr 中对应的num_layer默认为 2
2. OpenOCR默认的 config 中，默认开启amp，paddleocr 则默认关闭
3. no_weight_decay有差异
3. 两个框架的CPPD 网络有差异，包括 BN 层的 momentum、dropout的 prob等

在对齐 1,2 后，同一数据集下， CPPD在 paddleocr 和 openocr 训练效果有明显差异，如下图所示，同一个验证集上差 3 个点。
>  均为 4 x 128
![Image](https://github.com/user-attachments/assets/d617e2f6-93fc-4de7-9e7a-6ba382178165)

paddleocr config
```yaml
Global:
  use_gpu: True
  epoch_num: 32
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./output/rec/svtr_cppd_base_ch_from_scratch/
  save_epoch_step: 10
  # evaluation is run every 2000 iterations after the 0th iteration
  eval_batch_step: [0, 2000]
  cal_metric_during_train: False
  pretrained_model: 
  checkpoints:
  save_inference_dir:
  use_visualdl: True
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_svtr_cppd_base_ch_from_scratch_debug.txt



Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 1.e-8
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed char_node_embed pos_node_embed char_pos_embed vis_pos_embed
  one_dim_param_no_weight_decay: True
  lr:
    name: Cosine
    learning_rate: 0.0005 # 4gpus 128bs
    warmup_epoch: 5

Architecture:
  model_type: rec
  algorithm: CPPD
  Transform:
  Backbone:
    name: SVTRNet
    img_size: [32, 256]
    patch_merging: 'Conv'
    embed_dim: [128, 256, 384]
    depth: [6, 6, 4]
    num_heads: [4, 8, 12]
    mixer: ['Conv','Conv','Conv','Conv','Conv','Conv', 'Conv','Conv', 'Global','Global','Global','Global','Global','Global','Global','Global','Global','Global']
    local_mixer: [[5, 5], [5, 5], [5, 5]]
    last_stage: False
    prenorm: True
  Head:
    name: CPPDHead
    dim: 384
    vis_seq: 128
    ch: &ch True

Loss:
  name: CPPDLoss
  ignore_index: &ignore_index 7000 # must be greater than the number of character classes
  smoothing: True
  sideloss_weight: 1.0

PostProcess:
  name: CPPDLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /workspace/datasets/text_recog_1m/paddle_format_lenless25
    label_file_list:
    - /workspace/datasets/text_recog_1m/paddle_format_lenless25/train.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CPPDLabelEncode: # Class handling label
          ignore_index: *ignore_index
          ch: *ch
      - SVTRRecResizeImg:
          image_shape: [3, 32, 256]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'label_node', 'label_index', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 128
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /workspace/datasets/docr_rocr_dataset/std_recog_A_v1.2/paddle_format_lenless25
    label_file_list:
    - /workspace/datasets/docr_rocr_dataset/std_recog_A_v1.2/paddle_format_lenless25/labels.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CPPDLabelEncode: # Class handling label
          ignore_index: *ignore_index
          ch: *ch
      - SVTRRecResizeImg:
          image_shape: [3, 32, 256]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'label_node','label_index','length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 128
    num_workers: 2

```

Openocr config
```yaml
Global:
  device: gpu
  epoch_num: 32
  log_smooth_window: 20
  print_batch_step: 20
  output_dir: ./output/rec/ch/svtr_base_cppd_4x128_2/
  save_epoch_step: 10
  eval_batch_step: [0, 2000]
  eval_epoch_step: [0, 1]
  cal_metric_during_train: false
  pretrained_model: null
  checkpoints: null
  use_tensorboard: true
  infer_img: /workspace/datasets/docr_rocr_dataset/std_recog_A_v1.2/paddle_format_lenless25/images
  character_dict_path: ./tools/utils/ppocr_keys_v1.txt
  max_text_length: 25
  use_space_char: false
  save_res_path: ./output/rec/ch/predicts_svtr_base_cppd_4x128_2.txt
  use_amp: false
  project_name: OpenOCR
  run_name: svtr_base_cppd_ch_from_scratch_4x128_2
  distributed: true
Optimizer:
  name: AdamW
  betas:
  - 0.9
  - 0.99
  lr: 0.0005
  weight_decay: 0.05
  filter_bias_and_bn: true

LRScheduler:
  name: CosineAnnealingLR
  warmup_epoch: 5
Architecture:
  model_type: rec
  algorithm: CPPD
  in_channels: 3
  Transform: null
  Encoder:
    name: SVTRNet
    img_size:
    - 32
    - 256
    patch_merging: Conv
    embed_dim:
    - 128
    - 256
    - 384
    depth:
    - 6
    - 6
    - 4
    num_heads:
    - 4
    - 8
    - 12
    mixer:
    - Conv
    - Conv
    - Conv
    - Conv
    - Conv
    - Conv
    - Conv
    - Conv
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    local_mixer:
    - - 5
      - 5
    - - 5
      - 5
    - - 5
      - 5
    last_stage: false
    prenorm: true
  Decoder:
    name: CPPDDecoder
    vis_seq: 128
    num_layer: 2
    pos_len: false
    rec_layer: 1
    dim: 384
    ch: true
Loss:
  name: CPPDLoss
  ignore_index: 7000
  smoothing: true
  pos_len: false
  sideloss_weight: 1.0
PostProcess:
  name: CPPDLabelDecode
  character_dict_path: ./tools/utils/ppocr_keys_v1.txt
  use_space_char: false
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /workspace/datasets/text_recog_1m/paddle_format_lenless25
    label_file_list:
    - /workspace/datasets/text_recog_1m/paddle_format_lenless25/train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CPPDLabelEncode:
        pos_len: false
        ch: true
        ignore_index: 7000
        character_dict_path: ./tools/utils/ppocr_keys_v1.txt
        use_space_char: false
        max_text_length: 25
    - SVTRResize:
        image_shape:
        - 3
        - 32
        - 256
        padding: true
    - KeepKeys:
        keep_keys:
        - image
        - label
        - label_node
        - label_index
        - length
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /workspace/datasets/docr_rocr_dataset/std_recog_A_v1.2/paddle_format_lenless25
    label_file_list:
    - /workspace/datasets/docr_rocr_dataset/std_recog_A_v1.2/paddle_format_lenless25/labels.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CPPDLabelEncode:
        pos_len: false
        ch: true
        ignore_index: 7000
        character_dict_path: ./tools/utils/ppocr_keys_v1.txt
        use_space_char: false
        max_text_length: 25
    - SVTRResize:
        image_shape:
        - 3
        - 32
        - 256
        padding: true
    - KeepKeys:
        keep_keys:
        - image
        - label
        - label_node
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 256
    num_workers: 4
filename: svtr_base_cppd_ch
config: configs/rec/cppd/svtr_base_cppd_ch.yml
local_rank: null
eval: true
```

想知道 OpenOCR 中的 CPPD 是否有跟 PaddleOCR 中的 CPPD 严谨对齐，如果确实有差异，作者是否能更新对齐的代码，感谢！
